// ────────────────────────────────────────────
// ALL STATIC DATA - SUJAY CHAKRAVARTI PORTFOLIO
// Updated with latest LinkedIn & Professional Data
// ────────────────────────────────────────────

export const personalInfo = {
  name: "Sujay Chakravarti",
  title: "Full Stack Web Developer & Builder",
  headline:
    "Full Stack Web Developer | HTML, CSS, JS · Node.js · MongoDB · Firebase | Deploying Real Projects | Student & Builder",
  location: "Jalandhar, Punjab, India",
  email: "sujay983553@gmail.com",
  secondaryEmail: "sujayraj42@gmail.com",
  linkedin: "https://www.linkedin.com/in/sujay-2oo5",
  linkedinHandle: "sujay-2oo5",
  github: "https://github.com/sujayraj42",
  githubHandle: "sujayraj42",
  portfolio: "https://sujayraj42.github.io/sujay-portfolio-2026/",
  status: "OPEN_TO_WORK",
  roleStatus: "Open for Full Stack Roles & Engineering Internships",
  summary:
    "I'm Sujay Chakravarti, a self-driven Full Stack Web Developer and student who builds and deploys real-world web applications from scratch. My stack: Frontend → HTML, CSS, JavaScript, React · Backend → Node.js · Database → MongoDB, Firebase. I've taken projects from idea to live deployment — not just localhost projects, but real apps on the internet. Co-founder of Dev Krafters.",
};

export const experiences = [
  {
    id: 1,
    role: "Co-Founder & Full Stack Lead",
    company: "Dev Krafters",
    period: "September 2025 – Present",
    duration: "1 yr 1 mo",
    location: "Asia · Remote",
    badge: "AGENCY VENTURE",
    description:
      "Founded and lead a web development studio delivering custom websites, specialized tools, and high-impact web applications for growing local businesses.",
    highlights: [
      "Built and maintain a full-stack B2B application for Amrjeet Enterprise (a Supreme-authorized pipes & fittings dealer) using React on the frontend and Node.js on the backend with a global AppContext architecture.",
      "Developed an AI Photo Quotation Builder using the Gemini Vision API to auto-generate itemized quotes directly from product photos.",
      "Built a WhatsApp-to-quotation admin tool, B2B quote cart, and pipe/fitting calculator; automated GST-compliant PDF generation with Puppeteer.",
      "Extracted and structured a 185-SKU product catalog into a clean, image-embedded Excel dataset for web seeding.",
      "Authored full documentation suites (PRDs, UI/UX briefs, roadmaps) across a three-phase rollout: public storefront, admin dashboard, and B2B/contractor trade layer.",
      "Planned and ran digital marketing campaigns (Meta Ads, Instagram Reels, QR signage) to support client customer acquisition and led intern hiring.",
    ],
    tech: ["React", "Node.js", "Gemini Vision API", "Puppeteer", "Express", "Tailwind CSS", "MongoDB"],
  },
  {
    id: 2,
    role: "Full Stack Engineer",
    company: "Self-employed (Fiverr)",
    period: "2024 – Present",
    duration: "Ongoing",
    location: "Remote · Global Clients",
    badge: "INDEPENDENT CLIENTS",
    description:
      "Deliver independent web development services to clients outside core studio engagements, managing scope, timelines, architecture, and end-to-end delivery.",
    highlights: [
      "Engineered tailored web applications, landing pages, and interactive dashboards adhering to pixel-perfect design standards.",
      "Implemented clean REST APIs, database schemas, secure authentication flows, and responsive UI components with sub-second page performance.",
      "Managed direct client communications, milestone estimation, and post-launch maintenance with 100% on-time delivery record.",
    ],
    tech: ["React", "Node.js", "JavaScript", "HTML5", "CSS3", "Tailwind CSS", "REST APIs", "Git"],
  },
];

export const projects = [
  {
    id: 1,
    index: "01",
    name: "Amrjeet Enterprise B2B Platform",
    subtitle: "Supreme-Authorized Industrial Quoting & Trade Suite",
    starred: true,
    description:
      "Full-stack B2B industrial application engineered for Supreme-authorized dealer Amrjeet Enterprise. Features an AI Photo Quotation Builder using Google Gemini Vision API, WhatsApp admin sync, interactive pipe/fitting calculator, B2B quote cart, 185-SKU structured catalog, and automated GST-compliant PDF generation via Puppeteer.",
    tech: ["React", "Node.js", "Gemini Vision API", "Puppeteer", "Tailwind CSS", "Express"],
    github: "https://github.com/sujayraj42",
    live: null,
    year: "2025–2026",
    badge: "FLAGSHIP B2B",
  },
  {
    id: 2,
    index: "02",
    name: "MindGuard",
    subtitle: "Student Early-Risk Detection Portal",
    starred: true,
    description:
      "AI-powered full-stack mental health portal for students. Predicts at-risk students using behavioral pattern analysis, secure assessment tracking, and automated counselor alerts.",
    tech: ["JavaScript", "Node.js", "MongoDB", "REST APIs", "Express"],
    github: "https://github.com/sujayraj42/mindguard",
    live: null,
    year: "2026",
    badge: "AI HEALTHCARE",
  },
  {
    id: 3,
    index: "03",
    name: "Interactive Quiz App",
    subtitle: "Real-Time Assessment & Analytics Platform",
    starred: true,
    description:
      "Full-stack quiz engine with MongoDB, dynamic scoring algorithms, 20+ question categories, comprehensive quiz history, and user performance analytics dashboards.",
    tech: ["Node.js", "Express", "MongoDB", "JavaScript", "CSS3"],
    github: "https://github.com/sujayraj42/quizz-app",
    live: null,
    year: "2026",
    badge: "EDTECH",
  },
  {
    id: 4,
    index: "04",
    name: "TaskMaster REST API Engine",
    subtitle: "High-Throughput Enterprise Backend",
    starred: false,
    description:
      "Production-grade Node.js/Express backend service. Implements secure JWT authentication, granular role-based access control (RBAC), relational MySQL schema, rate limiting, and cursor-based pagination.",
    tech: ["Node.js", "Express", "MySQL", "JWT", "REST APIs"],
    github: "https://github.com/sujayraj42",
    live: null,
    year: "2026",
    badge: "BACKEND ARCHITECTURE",
  },
  {
    id: 5,
    index: "05",
    name: "MediCare Cross-Platform Portal",
    subtitle: "Modern Patient Care & Scheduling Application",
    starred: false,
    description:
      "Cross-platform Ionic healthcare application with automated doctor appointment booking, patient lab report viewing, medical history logs, and multi-page routing.",
    tech: ["Ionic", "Angular", "HTML5", "CSS3", "TypeScript"],
    github: "https://github.com/sujayraj42",
    live: null,
    year: "2026",
    badge: "MOBILE & WEB",
  },
  {
    id: 6,
    index: "06",
    name: "Real-Time Weather Dashboard",
    subtitle: "Geolocated Forecast & Ambient Visuals",
    starred: false,
    description:
      "Meteorological analytics dashboard utilizing the OpenWeatherMap API, HTML5 geolocation, 7-day extended forecasts, and time-aware dynamic CSS weather animations.",
    tech: ["JavaScript", "Tailwind CSS", "REST APIs", "HTML5"],
    github: "https://github.com/sujayraj42",
    live: null,
    year: "2026",
    badge: "API INTEGRATION",
  },
  {
    id: 7,
    index: "07",
    name: "Personal Portfolio v1 (Zero Frameworks)",
    subtitle: "Handcrafted Particle & Canvas Experience",
    starred: false,
    description:
      "Engineered completely from scratch in pure vanilla JS and CSS with zero frameworks. Features an interactive physics particle simulation offloaded to Web Workers and OffscreenCanvas.",
    tech: ["HTML5", "CSS3", "JavaScript ES2025+", "Canvas API"],
    live: "https://port2-nine-swart.vercel.app/",
    github: "https://github.com/sujayraj42/port2",
    year: "2026",
    badge: "CREATIVE CODING",
  },
  {
    id: 8,
    index: "08",
    name: "OAKWood's Furniture E-Commerce",
    subtitle: "Artisanal Home Decor Storefront",
    starred: false,
    description:
      "Modern e-commerce UI featuring fluid CSS grid layouts, smooth micro-interactions, responsive product filters, and interactive product showcase galleries.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    live: "https://oakwood-furniture.vercel.app/",
    github: "https://github.com/sujayraj42/OAKWood-s-Furniture-Website",
    year: "2024",
    badge: "E-COMMERCE",
  },
  {
    id: 9,
    index: "09",
    name: "Explore Varanasi — Spiritual Capital",
    subtitle: "Interactive Heritage & Cultural Tourism Portal",
    starred: false,
    description:
      "Cultural tourism web platform with interactive Google Maps API integration, heritage monuments catalog, lightbox photo exhibits, and historical walkthroughs.",
    tech: ["Bootstrap 5", "HTML5", "CSS3", "Google Maps API"],
    live: "https://sujayraj42.github.io/Explore-Varanasi---The-Spiritual-Capital/",
    github: "https://github.com/sujayraj42/Explore-Varanasi---The-Spiritual-Capital",
    year: "2024",
    badge: "GEO & TOURISM",
  },
];

export const certifications = [
  {
    id: 1,
    name: "Introduction to Android Mobile Application Development",
    issuer: "Meta",
    platform: "Coursera",
    date: "2025",
    credentialId: null,
    verifyUrl: null,
    accent: "primary",
  },
  {
    id: 2,
    name: "Introduction to Web Development",
    issuer: "UC Davis",
    platform: "Coursera",
    date: "June 2025",
    credentialId: "MNQQHK6QJ1SO",
    verifyUrl:
      "https://www.coursera.org/account/accomplishments/verify/MNQQHK6QJ1SO",
    accent: "primary",
  },
  {
    id: 3,
    name: "Introduction to HTML5",
    issuer: "University of Michigan",
    platform: "Coursera",
    date: "2025",
    credentialId: null,
    verifyUrl: null,
    accent: "secondary",
  },
  {
    id: 4,
    name: "Introduction to CSS3",
    issuer: "University of Michigan",
    platform: "Coursera",
    date: "2025",
    credentialId: null,
    verifyUrl: null,
    accent: "secondary",
  },
  {
    id: 5,
    name: "C for Everyone: Programming Fundamentals",
    issuer: "UC Santa Cruz",
    platform: "Coursera",
    date: "2025",
    credentialId: null,
    verifyUrl: null,
    accent: "tertiary",
  },
  {
    id: 6,
    name: "Technical Support Fundamentals",
    issuer: "Google",
    platform: "Coursera",
    date: "June 2025",
    credentialId: "5EFFZDVAOXU6",
    verifyUrl:
      "https://www.coursera.org/account/accomplishments/verify/5EFFZDVAOXU6",
    accent: "primary",
  },
  {
    id: 7,
    name: "Interactivity with JavaScript",
    issuer: "University of Michigan",
    platform: "Coursera",
    date: "2025",
    credentialId: null,
    verifyUrl: null,
    accent: "secondary",
  },
  {
    id: 8,
    name: "Student Volunteer Recognition",
    issuer: "LPU",
    platform: "Freshmen Induction 2025",
    date: "2025",
    credentialId: null,
    verifyUrl: null,
    accent: "tertiary",
  },
];

export const education = [
  {
    id: 1,
    degree: "Master of Computer Applications (MCA)",
    institution: "Dev Bhoomi Uttarakhand University",
    range: "Enrolled / Upcoming",
    detail: "Postgraduate studies in Advanced Software Architecture, Cloud Systems & Computer Applications",
    url: null,
    active: true,
  },
  {
    id: 2,
    degree: "Bachelor of Computer Applications (BCA)",
    institution: "Lovely Professional University (LPU)",
    range: "August 2023 – April 2026",
    detail: "Computer Science · Full Stack Web Development · Core Programming · 83.75% Aggregate",
    url: "https://www.lpu.in/",
    active: true,
  },
  {
    id: 3,
    degree: "Advance Diploma in Computer Application (ADCA)",
    institution: "Parmar Commercial Institute",
    range: "March 2022 – April 2023",
    detail: "Computer Science, Software Tools & Database Management",
    url: null,
    active: false,
  },
  {
    id: 4,
    degree: "Higher Secondary (12th) — CBSE Science",
    institution: "D.Y. Patil Pushpalata Patil International School",
    range: "Completed 2022",
    detail: "Physics, Chemistry, Mathematics & Computer Science",
    url: null,
    active: false,
  },
];

export const events = [
  {
    id: 1,
    name: "8th Chhatra Sansad India Conclave",
    role: "Stage Manager",
    stat: "20,000+",
    statLabel: "attendees",
    reactions: "165",
    description: "Managed mainstage proceedings, VIP speaker cueing, and live technical coordination at India's largest youth parliamentary conclave.",
    speakers: [
      "Smriti Irani",
      "Khan Sir",
      "Dr. V Narayanan (ISRO)",
      "Jaya Kishori",
      "Temjen Imna Along",
    ],
  },
  {
    id: 2,
    name: "International Women's Day Celebration — LPU",
    role: "Stage Manager",
    stat: "1,500+",
    statLabel: "attendees",
    reactions: "88",
    description: "Orchestrated stage operations, VIP dignitary arrivals, and sound/lighting execution for the annual flagship celebration.",
    speakers: ["Dr. Rashmi Mittal (Pro Chancellor, LPU)"],
  },
  {
    id: 3,
    name: "Youth Talk ft. Gaurav Taneja (FlyingBeast) — LPU",
    role: "Stage Manager",
    stat: "2,500+",
    statLabel: "attendees",
    reactions: "157",
    description: "Coordinated celebrity security, audio-visual technical handoffs, and audience Q&A flow for over 2,500 students.",
    speakers: ["Gaurav Taneja (YouTuber, Aviator)"],
  },
  {
    id: 4,
    name: "Gita Olympiad National Prize Distribution — LPU",
    role: "Event Lead",
    stat: "2,000+",
    statLabel: "participants",
    reactions: "229",
    description: "Led the volunteer committee of 30+ students managing logistics, stage setup, felicitation ceremony, and hall coordination.",
    speakers: ["Bhakt Bhagwat", "H.G. Dr. Vrindavan Chandra Das"],
  },
];

export const skills = {
  topSkills: ["Cypress", "REST APIs", "Tailwind CSS"],
  languages: [
    { name: "HTML5", level: 95, desc: "Semantic markup, accessibility & SEO" },
    { name: "CSS3", level: 90, desc: "Animations, Tailwind, Grid & Flexbox" },
    { name: "JavaScript", level: 92, desc: "ES2025+, DOM, async/await, APIs" },
    { name: "TypeScript", level: 85, desc: "Strict types, interfaces & safety" },
    { name: "C", level: 75, desc: "Data structures & memory fundamentals" },
  ],
  frameworks: [
    "React",
    "Node.js",
    "Express",
    "Tailwind CSS",
    "Cypress",
    "MongoDB",
    "Firebase",
    "MySQL",
    "REST APIs",
    "Puppeteer",
    "Gemini Vision API",
    "Framer Motion",
    "GSAP",
    "Lenis",
    "Three.js",
    "Git & GitHub",
    "Figma",
    "Vite",
  ],
  backendLines: [
    "> stack: Node.js · Express · MongoDB · Firebase · MySQL",
    "> apis: RESTful · JWT auth · RBAC · Puppeteer PDF engine",
    "> ai tooling: Google Gemini Vision API integrated into production",
    "> testing: Cypress E2E automated test suites",
    "> status: OPEN_TO_WORK — Ready to ship high-impact code",
  ],
  softSkills: [
    { name: "Founder & Builder Mindset", size: "large" },
    { name: "Stage Management (20,000+)", size: "large" },
    { name: "Team Leadership", size: "large" },
    { name: "Client Collaboration", size: "medium" },
    { name: "PRDs & Architecture Specs", size: "medium" },
    { name: "Public Speaking", size: "medium" },
    { name: "Problem Solving", size: "medium" },
    { name: "Time Management", size: "small" },
    { name: "Adaptability", size: "small" },
  ],
};

export const aboutStats = [
  { value: "1", label: "Studio Co-Founded" },
  { value: "9", label: "Shipped Projects" },
  { value: "20K+", label: "Conclave Attendees" },
  { value: "500+", label: "Tech Network" },
];

export const navLinks = [
  { label: "ABOUT", href: "#about" },
  { label: "EXPERIENCE", href: "#experience" },
  { label: "WORK", href: "#work" },
  { label: "SKILLS", href: "#skills" },
  { label: "EVENTS", href: "#events" },
  { label: "CERTS", href: "#certs" },
  { label: "EDUCATION", href: "#education" },
  { label: "CONTACT", href: "#contact" },
];
